### ISSUE TITLE
Django needs python 2.7

### ISSUE THREAD

**Issue by wimvandijck** [geerlingguy/ansible-for-devops#13]
Following the instructions, python 2.6 is installed, however django 1.8 requires 2.7.

Installing django with easy_install will result in this error:
```
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.10', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1715, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1696, in with_ei_usage
    return f()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1719, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 32, in <module>
  File "/tmp/easy_install-wlw1To/Django-1.8/django/__init__.py", line 1, in <module>
  File "/tmp/easy_install-wlw1To/Django-1.8/django/utils/version.py", line 7, in <module>
  File "/tmp/easy_install-wlw1To/Django-1.8/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax

```
Installing with pip will work, but then execution will fail with the same error.

**Comment by geerlingguy** [comment]
@wimvandijck - Which example is this for? Also, can you give more detail as to what OS you're running, and how you're setting things up?

**Comment by wimvandijck** [comment]
Yep, sorry for missing that!
OSX Darwin Kernel Version 14.1.0
Example from chapter 3 Ad-Hoc Commands

I installed the vagrant box per the instructions.
Then at the point where I do 
```
ansible app -s -m easy_install -a "name=django"
```
I get the above errors.
Actually, the precise errors above I got by vagrant ssh into them, and manually trying to install django.
I discovered in the meantime that CentOS comes with python 2.6, and the latest django requires at least 2.7.
So I got around it, by manually install a more recent version of python (compiling from source), and using that to install django.
hth

**Comment by geerlingguy** [comment]
Helps quite a bit, thanks! I'll update the example in the book so it works out of the box. I'll post back here when that's complete.

**Comment by geerlingguy** [comment]
@wimvandijck - Thanks for reporting this! I've updated the example in the book now, and last time I ran it Django was at 1.6.1, which did run with CentOS 6.x's outdated Python version. The example now uses CentOS 7, which has Python 2.7.5.

Would you like a credit in the book's changelog for this correction/suggestion? If so, can I just reference @wimvandijck?

**Comment by wimvandijck** [comment]
Glad to help! Good to hear it was easy to fix! :) That'd be awesome :D go ahead.
