### ISSUE TITLE
Travis CI build failing for deployments-rolling.yml playbook

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#134]
Failed build: https://travis-ci.org/geerlingguy/ansible-for-devops/jobs/503918765

```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["npm", "test"], "delta": "0:00:01.155195", "end": "2019-03-09 13:46:11.873856", "msg": "non-zero return code", "rc": 1, "start": "2019-03-09 13:46:10.718661", "stderr": "/opt/demo-nodejs-api/node_modules/csv-parse/lib/index.js:19
    super({...{readableObjectMode: true}, ...opts})
           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/csv/lib/index.js:6:10)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/plugins/fieldedTextBodyParser.js:7:11)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/plugins/bodyParser.js:12:25)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/plugins/index.js:11:17)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/index.js:115:26)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/demo-nodejs-api/app.js:2:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/demo-nodejs-api/test/hello.js:2:11)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /opt/demo-nodejs-api/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (native)
    at Mocha.loadFiles (/opt/demo-nodejs-api/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/opt/demo-nodejs-api/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
npm ERR! Test failed.  See above for more details.", "stderr_lines": ["/opt/demo-nodejs-api/node_modules/csv-parse/lib/index.js:19", "    super({...{readableObjectMode: true}, ...opts})", "           ^^^", "", "SyntaxError: Unexpected token ...", "    at createScript (vm.js:56:10)", "    at Object.runInThisContext (vm.js:97:10)", "    at Module._compile (module.js:549:28)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/csv/lib/index.js:6:10)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/plugins/fieldedTextBodyParser.js:7:11)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/plugins/bodyParser.js:12:25)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/plugins/index.js:11:17)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/restify/lib/index.js:115:26)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/demo-nodejs-api/app.js:2:15)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/demo-nodejs-api/test/hello.js:2:11)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.require (module.js:504:17)", "    at require (internal/module.js:20:19)", "    at /opt/demo-nodejs-api/node_modules/mocha/lib/mocha.js:250:27", "    at Array.forEach (native)", "    at Mocha.loadFiles (/opt/demo-nodejs-api/node_modules/mocha/lib/mocha.js:247:14)", "    at Mocha.run (/opt/demo-nodejs-api/node_modules/mocha/lib/mocha.js:576:10)", "    at Object.<anonymous> (/opt/demo-nodejs-api/node_modules/mocha/bin/_mocha:637:18)", "    at Module._compile (module.js:577:32)", "    at Object.Module._extensions..js (module.js:586:10)", "    at Module.load (module.js:494:32)", "    at tryModuleLoad (module.js:453:12)", "    at Function.Module._load (module.js:445:3)", "    at Module.runMain (module.js:611:10)", "    at run (bootstrap_node.js:387:7)", "    at startup (bootstrap_node.js:153:9)", "    at bootstrap_node.js:500:3", "npm ERR! Test failed.  See above for more details."], "stdout": "
> examplenodejsapi@ test /opt/demo-nodejs-api
> mocha test --exit", "stdout_lines": ["", "> examplenodejsapi@ test /opt/demo-nodejs-api", "> mocha test --exit"]}
```

**Comment by geerlingguy** [comment]
Also found that the build was failing with VirtualBox/Vagrant because apt needed updating.

**Comment by geerlingguy** [comment]
That's odd... the tests are passing fine when run locally. Maybe an issue in the Docker image?

**Comment by geerlingguy** [comment]
Testing with the test shim and Docker locally now.

**Comment by geerlingguy** [comment]
Hmm, for some reason in the Docker container it's installing Node.js version 6.x; maybe it's preinstalled on there for some reason? The default in the `geerlingguy.nodejs` role is `nodejs_version: "8.x"`...

**Comment by geerlingguy** [comment]
It's actually `10.x` but I had not tagged a new release of the role... doing so now and will re-run the test.

**Comment by geerlingguy** [comment]
(Special thanks to this comment: https://github.com/adaltas/node-csv-parse/issues/183#issuecomment-375473229)

**Comment by geerlingguy** [comment]
Fixed by upgrading Node.js to 10.x. Weird that it was working differently on local VM vs docker. Both are minimal Ubuntu 18.04.

Committing update to add apt cache update to main playbook too.
