### ISSUE TITLE
Convert CI from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#359]
Rationale: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by geerlingguy** [comment]
Hmm... the `deployments-rolling.yml` test playbook is failing on some Node.js tests:

```
> examplenodejsapi@ test /opt/demo-nodejs-api
> mocha test --exit



restify listening at http://[::]:8080
  Hello
    /hello/:name endpoint
      ✓ returns a welcome message based on the name

  Ping
    /ping/:server endpoint
      1) tells us when a server is reachable

  Ping
    /ping/:server endpoint
      2) tells us when a server is unreachable


  1 passing (2s)
  2 failing

  1) Ping
       /ping/:server endpoint
         tells us when a server is reachable:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure \"done()\" is called; if returning a Promise, ensure it resolves. (/opt/demo-nodejs-api/test/ping.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Ping
       /ping/:server endpoint
         tells us when a server is unreachable:
     Uncaught AssertionError: Body

    Actual:   '\"google.com is unreachable.\"'
    Expected: /\"google.com is reachable/

      at assert (node_modules/hippie/lib/hippie/assert.js:36:10)
      at value (node_modules/hippie/lib/hippie/expect.js:92:10)
      at verify (node_modules/hippie/lib/hippie/client.js:476:5)
      at statusCode (node_modules/hippie/lib/hippie/expect.js:23:5)
      at verify (node_modules/hippie/lib/hippie/client.js:476:5)
      at Client.verify (node_modules/hippie/lib/hippie/client.js:477:5)
      at /opt/demo-nodejs-api/node_modules/hippie/lib/hippie/client.js:437:12
      at Client.exports.raw [as parse] (node_modules/hippie/lib/hippie/parsers.js:33:3)
      at Request._callback (node_modules/hippie/lib/hippie/client.js:435:10)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:483:12)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at Request.EventEmitter.emit (domain.js:483:12)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at IncomingMessage.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by geerlingguy** [comment]
Running those tests locally works:

```
$ npm test

> test
> mocha test --exit



restify listening at http://[::]:8080
  Hello
    /hello/:name endpoint
      ✓ returns a welcome message based on the name

  Ping
    /ping/:server endpoint
      ✓ tells us when a server is reachable (41ms)

  Ping
    /ping/:server endpoint
      ✓ tells us when a server is unreachable


  3 passing (105ms)
```

Building and running in the Vagrant environment seems to break though:

```
Uncaught Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

A different error in each case, maybe an environment issue or a Node.js version issue :-/

**Comment by geerlingguy** [comment]
Inside Vagrant:

```
$ node --version
v12.20.0
```

On localhost:

```
$ node --version
v15.3.0
```

**Comment by geerlingguy** [comment]
Disabled that test for now :/

**Comment by geerlingguy** [comment]
And the `jenkins.yml` playbook is hitting:

```
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
changed: [localhost] => (item=ansicolor)
```

Which is breaking idempotence :(

**Comment by geerlingguy** [comment]
Now the `includes.yml` playbook is hitting:

```
fatal: could not create leading directories of '/var/www/.cache/composer/vcs/https---git.drupalcode.org-project-coder.git
```

In the task `Install Drupal dependencies with Composer.`.

_le sigh_

**Comment by geerlingguy** [comment]
Created follow-up issue now that tests are green: https://github.com/geerlingguy/ansible-for-devops/issues/361
