### ISSUE TITLE
CI builds for docker-hubot example are currently failing

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#403]
Getting:

```
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:533
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/router.js:8:27)
```

When it tries to generate the bot with `yo hubot`.

Confirmed locally by running `playbook=docker-hubot.yml distro=ubuntu2004 tests/test.sh`.

**Comment by geerlingguy** [comment]
Wondering if maybe `yo` is now incompatible with Node.js v8 which is the version used in that playbook. Maybe updating to v14 (current LTS) is a good idea?

**Comment by geerlingguy** [comment]
Yay, fixed!
